### ISSUE TITLE
Add option to preserve directory structure

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [malchata/rollup-plugin-imagemin#2]
First, thank you this is an excellent plugin.

Now, I have a problem.
My project dynamically loads images based on current page and image subdirectory.
So storing all images in a flat, one-directory structure plain doesn't work.

I forked this repo and added this feature in `preserveTree` branch, so if you're OK with this I can make a pull request. I also added additional tests to ensure it works.

Side note: I had to rename files from `.mjs` to `.js`, because the tests wouldn't run otherwise.

**Comment by malchata** [comment]
Hey, @OzymandiasTheGreat!

Sorry for my delayed response. I was traveling abroad.

I'm interested in seeing this added, because I think it's relevant. If you want to write some tests and do a PR, I'm interested in reviewing and merging, pending feedback/reviews.

Thanks!

**Comment by malchata** [comment]
Resolved by merging #3.
